// This file is auto-generated by Convex
// Run `npx convex dev` to regenerate

import type { AnyApi } from "convex/api";

// Placeholder - will be replaced when you run convex dev
export const api = {} as AnyApi;
